version: '3'
services:
  webserver:
    container_name: webserver
    build: .
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - database
    ports:
      - 8080:80
  database:
    container_name: database
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech
    volumes:
      - ./database:/var/lib/postgresql